### ISSUE TITLE
asyncHandler, second callback argument name 'b'- types of return value

### ISSUE THREAD

**Issue by mjaracz** [EthWorks/restless#26]
In my personal project I have this usage of restless solutions:
my point of Route, method post:
```
route.post('/login', asyncHandler( sanitize({
    body: asObject({
      username: asString,
      password: asString,
    })
  }),
  (reqData) => {
  const {username, password} = reqData.body;
  findUser('user', username)
    .then((user: User) => {
      if(user.password === password) {
        responseOf(user, 200)
      }
      else {
        responseOf('user not found', 400)
      }
    })
    .catch(err => {
      responseOf('internal server error', 500)
    })
  }
));
````
TypeScript compiler error:
`Type void is not assignable to type ResponseFunction | Promise<ResponseFunction> `

When I change code to marked returns type like belowe
`
...
function(reqData): ResponseFunction | Promise<ResponseFunction> {
...
`
I have another ts compiler warrning

Does anyone have any idea how to solve this issue?

**Comment by sz-piotr** [comment]
`asyncHandler` expects that the last argument is a function that returns `ResponseFunction | Promise<ResponseFunction>`. This means that you need to use the `return` keyword instead of just calling `responseOf`.

Try this
```typescript
.then((user: User) => {
  if(user.password === password) {
    return responseOf(user, 200)
  }
  else {
    return responseOf('user not found', 400)
  }
})
.catch(err => {
  return responseOf('internal server error', 500)
})
```
